"""cost items and history

Revision ID: 0004_cost_items_history
Revises: 0003_applications_vendors_services
Create Date: 2026-08-19 17:34:26.559621
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_cost_items_history"
down_revision: str | None = "0003_applications_vendors_services"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column(
            "billing_type",
            sa.Enum(
                "fixed",
                "usage",
                "one_time",
                name="billingtype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "weekly",
                "monthly",
                "quarterly",
                "yearly",
                "custom",
                name="frequency",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "ended",
                name="coststatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "certainty",
            sa.Enum(
                "confirmed",
                "estimated",
                "projected",
                name="certainty",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_cost_item_amount_positive"),
        sa.ForeignKeyConstraint(
            ["application_id"], ["application.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"], ["environment.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_item_application_id"),
        "cost_item",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_item_category"), "cost_item", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_cost_item_certainty"), "cost_item", ["certainty"], unique=False
    )
    op.create_index(
        op.f("ix_cost_item_environment_id"),
        "cost_item",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_item_service_id"), "cost_item", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_cost_item_status"), "cost_item", ["status"], unique=False)
    op.create_index(
        op.f("ix_cost_item_workspace_id"), "cost_item", ["workspace_id"], unique=False
    )
    op.create_table(
        "cost_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cost_item_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["cost_item_id"], ["cost_item.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cost_history_cost_item_id"),
        "cost_history",
        ["cost_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cost_history_cost_item_id"), table_name="cost_history")
    op.drop_table("cost_history")
    op.drop_index(op.f("ix_cost_item_workspace_id"), table_name="cost_item")
    op.drop_index(op.f("ix_cost_item_status"), table_name="cost_item")
    op.drop_index(op.f("ix_cost_item_service_id"), table_name="cost_item")
    op.drop_index(op.f("ix_cost_item_environment_id"), table_name="cost_item")
    op.drop_index(op.f("ix_cost_item_certainty"), table_name="cost_item")
    op.drop_index(op.f("ix_cost_item_category"), table_name="cost_item")
    op.drop_index(op.f("ix_cost_item_application_id"), table_name="cost_item")
    op.drop_table("cost_item")
    # ### end Alembic commands ###
