"""evidence and expense

Revision ID: 0005_evidence_expense
Revises: 0004_cost_items_history
Create Date: 2026-08-19 18:32:30.949353
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005_evidence_expense"
down_revision: str | None = "0004_cost_items_history"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "invoice",
                "receipt",
                "contract",
                "screenshot",
                "other",
                name="evidencetype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=120), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_evidence_workspace_id"), "evidence", ["workspace_id"], unique=False
    )
    op.create_table(
        "expense",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("cost_item_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("paid_at", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "paid",
                "failed",
                "refunded",
                name="expensestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("invoice_number", sa.String(length=120), nullable=True),
        sa.Column("evidence_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_expense_amount_positive"),
        sa.ForeignKeyConstraint(["cost_item_id"], ["cost_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_cost_item_id"), "expense", ["cost_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_expense_evidence_id"), "expense", ["evidence_id"], unique=False
    )
    op.create_index(op.f("ix_expense_status"), "expense", ["status"], unique=False)
    op.create_index(
        op.f("ix_expense_workspace_id"), "expense", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_workspace_id"), table_name="expense")
    op.drop_index(op.f("ix_expense_status"), table_name="expense")
    op.drop_index(op.f("ix_expense_evidence_id"), table_name="expense")
    op.drop_index(op.f("ix_expense_cost_item_id"), table_name="expense")
    op.drop_table("expense")
    op.drop_index(op.f("ix_evidence_workspace_id"), table_name="evidence")
    op.drop_table("evidence")
    # ### end Alembic commands ###
